/** Target search phrases — reuse across page metadata */
export const SEO_KEYWORDS = {
  home: [
    'bulk certificate generator',
    'free certificate maker',
    'certificate automation',
    'send certificates by email',
    'google forms certificates',
    'hackathon certificate generator',
    'privacy first certificate tool',
    'browser based PDF generator',
    'mail certificates gmail',
    'event certificate generator',
    'certificate generator open source',
    'bulk certificate maker',
    'free certificate generator no signup',
    'certificate generator no watermark',
    'local first certificate tool',
    'certificate mail merge',
    'personalized certificate generator',
    'batch certificate generator',
    'Akshat Thakur',
    'MailMyCertificate by Akshat Thakur',
  ],
  guide: [
    'how to generate certificates in bulk',
    'google sheets certificate mail merge',
    'csv certificate generator tutorial',
    'gmail bulk certificate send',
    'canva certificate automation',
    'workshop certificate generator guide',
    'bulk certificate generation tutorial',
    'certificate generator step by step',
    'how to automate certificates',
    'certificate workflow automation',
  ],
  about: [
    'open source certificate generator',
    'mail my certificate about',
    'privacy first event tools',
    'Akshat Thakur',
    'Akshat Thakur software developer',
    'Akshat Thakur GitHub',
    'Akshat Thakur portfolio',
    'Akshat Thakur open source',
    'Akshat Thakur web developer',
    'Akshat Thakur projects',
    'who built MailMyCertificate',
    'local first certificate architecture',
  ],
  contact: ['mail my certificate contact', 'certificate tool support', 'certificate generator help'],
  privacy: [
    'mail my certificate privacy policy',
    'local first certificate data',
    'certificate generator privacy',
    'gdpr compliant certificate tool',
    'privacy first certificate generator',
    'certificate data protection',
  ],
  terms: ['mail my certificate terms of service', 'certificate generator terms'],

  googleSheets: [
    'google sheets certificate generator',
    'google forms to certificates',
    'google sheets mail merge certificates',
    'bulk certificates from spreadsheet',
    'generate certificates from google sheets',
    'google forms certificate automation',
    'privacy first google sheets certificates',
    'google sheets certificate template',
    'google sheets to pdf certificates',
    'google forms responses to certificates',
    'certificate generator google sheets integration',
    'mail merge google sheets gmail',
  ],
  googleForms: [
    'google forms to certificates',
    'google forms certificate generator',
    'automate certificates from google forms',
    'google form responses certificates',
    'certifyem alternative',
    'google forms certificate email',
    'google forms certificate add on alternative',
    'certificate generator for google forms',
    'google forms mail merge certificates',
    'automate google forms certificates',
  ],
  gmailBulk: [
    'send certificates by email gmail',
    'bulk certificate email gmail',
    'gmail bulk certificate send',
    'personalized certificate email attachments',
    'mail merge certificates gmail',
    'gmail mass email with attachments',
    'send bulk pdfs gmail',
    'gmail certificate delivery',
    'bulk email certificates',
  ],
  hackathon: [
    'hackathon certificate generator',
    'bulk hackathon certificates',
    'coding competition certificates',
    'send hackathon certificates email',
    'free hackathon certificate tool',
    'devfolio certificate generator',
    'unstop certificate generator',
    'mlh certificate maker',
    'tech fest certificates bulk',
    'coding event certificates',
    'hackathon participation certificate',
    'winner certificate generator',
  ],
  canvaAlternative: [
    'canva certificate alternative',
    'canva certificate automation',
    'bulk certificates without manual canva',
    'canva mail merge certificates',
    'canva certificate export bulk',
    'automate canva certificates',
    'canva bulk certificate generator',
    'certificate generator after canva',
  ],
  certifierComparison: [
    'mailmycertificate vs certifier',
    'certifier alternative free',
    'certifier comparison',
    'bulk certificate generator comparison',
    'free alternative to certifier',
    'certifier free version',
  ],

  // New pages
  canvaComparison: [
    'mailmycertificate vs canva',
    'canva certificate bulk export',
    'canva alternative for bulk certificates',
    'automate canva certificate generation',
    'canva certificate without manual edit',
    'canva bulk pdf generator',
    'better than canva for certificates',
    'canva certificate limitation bulk',
  ],
  certifyemComparison: [
    'certifyem alternative',
    'google forms certificate add on alternative',
    'mailmycertificate vs certifyem',
    'certifyem free alternative',
    'certificate generator without google add on',
    'privacy alternative to certifyem',
    'certifyem open source alternative',
  ],
  workshop: [
    'workshop certificate generator',
    'free workshop certificate maker',
    'bulk workshop certificates',
    'workshop participation certificate',
    'workshop certificate email',
    'online workshop certificate generator',
    'workshop organizer certificate tool',
    'training workshop certificate',
    'certificate generator for workshops',
  ],
  webinar: [
    'webinar certificate generator',
    'free webinar certificate maker',
    'bulk webinar certificates',
    'webinar participation certificate',
    'online webinar certificate',
    'zoom webinar certificate generator',
    'webinar attendance certificate',
    'send webinar certificates gmail',
  ],
  excelCsv: [
    'certificate generator from excel',
    'bulk certificates from csv',
    'excel to certificate generator',
    'csv mail merge certificates',
    'spreadsheet to pdf certificates',
    'generate certificates from excel sheet',
    'certificate generator from spreadsheet',
    'bulk pdf from excel free',
    'certificate mail merge from csv',
  ],
  templates: [
    'free certificate templates download',
    'certificate template png free',
    'blank certificate template',
    'hackathon certificate template',
    'workshop certificate template',
    'certificate border design png',
    'certificate of participation template',
    'certificate of achievement template',
    'winner certificate template',
    'minimalist certificate template',
  ],
  blog: [
    'certificate automation guide',
    'bulk certificate tips',
    'event organizer tools blog',
    'certificate generator tutorial',
    'how to make certificates',
  ],
  blogHowToEvents: [
    'how to make certificates for events',
    'event certificate guide',
    'bulk certificate creation tutorial',
    'certificate generation guide 2026',
    'how to issue certificates for events',
    'certificate organizer workflow',
    'event certificate automation',
    'how to create certificates in bulk',
  ],
  blogSendCertificates: [
    'how to send certificates to participants',
    'certificate delivery best practices',
    'bulk email certificates to participants',
    'how to distribute certificates',
    'send certificates after event',
    'gmail certificate delivery guide',
  ],
  blogBestGenerators: [
    'best free certificate generators',
    'best bulk certificate generator 2026',
    'certificate generator comparison 2026',
    'top certificate maker tools',
    'free vs paid certificate generators',
    'certificate generator review',
    'certifier alternative list',
    'best certificate tool for events',
  ],
} as const;
