/** Target search phrases — reuse across page metadata */
export const SEO_KEYWORDS = {
  home: [
    'bulk certificate generator',
    'free certificate maker',
    'certificate automation',
    'send certificates by email',
    'google forms certificates',
    'hackathon certificate generator',
    'privacy first certificate tool',
    'browser based PDF generator',
    'mail certificates gmail',
    'event certificate generator',
  ],
  guide: [
    'how to generate certificates in bulk',
    'google sheets certificate mail merge',
    'csv certificate generator tutorial',
    'gmail bulk certificate send',
    'canva certificate automation',
    'workshop certificate generator guide',
  ],
  about: [
    'open source certificate generator',
    'mail my certificate about',
    'privacy first event tools',
  ],
  contact: ['mail my certificate contact', 'certificate tool support'],
  privacy: ['mail my certificate privacy policy', 'local first certificate data'],
  terms: ['mail my certificate terms of service'],
  googleSheets: [
    'google sheets certificate generator',
    'google forms to certificates',
    'google sheets mail merge certificates',
    'bulk certificates from spreadsheet',
    'generate certificates from google sheets',
    'google forms certificate automation',
    'privacy first google sheets certificates',
  ],
  googleForms: [
    'google forms to certificates',
    'google forms certificate generator',
    'automate certificates from google forms',
    'google form responses certificates',
    'certifyem alternative',
    'google forms certificate email',
  ],
  gmailBulk: [
    'send certificates by email gmail',
    'bulk certificate email gmail',
    'gmail bulk certificate send',
    'personalized certificate email attachments',
    'mail merge certificates gmail',
  ],
  hackathon: [
    'hackathon certificate generator',
    'bulk hackathon certificates',
    'coding competition certificates',
    'send hackathon certificates email',
    'free hackathon certificate tool',
  ],
  canvaAlternative: [
    'canva certificate alternative',
    'canva certificate automation',
    'bulk certificates without manual canva',
    'canva mail merge certificates',
  ],
  certifierComparison: [
    'mailmycertificate vs certifier',
    'certifier alternative free',
    'certifier comparison',
    'bulk certificate generator comparison',
  ],
} as const;
