import { ContentLayout } from '@/components/layout/ContentLayout';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Disclaimer',
    description: 'Important legal notices and limitation of liability for MailMyCertificate.',
};

export default function Disclaimer() {
    return (
        <ContentLayout
            title="Disclaimer"
            subtitle="Please read this carefully before using the tool for mission-critical tasks."
        >
            <section>
                <h2>1. No Legal Validity</h2>
                <p>
                    The certificates generated by MailMyCertificate are for informational and ceremonial purposes only.
                    MailMyCertificate is not a certification authority. We do not verify the authenticity of the contents or
                    the authority of the issuer.
                </p>
            </section>

            <section>
                <h2>2. "As-Is" Software</h2>
                <p>
                    This is a free, open-source tool. While we strive for 100% stability, we do not guarantee that the service will be
                    uninterrupted or error-free. You use this tool at your own risk.
                </p>
            </section>

            <section>
                <h2>3. Not a Backup Service</h2>
                <p>
                    MailMyCertificate uses temporary browser storage (IndexedDB). It is <strong>NOT</strong> a permanent storage or
                    backup solution. Once you clear your browser data or use a different device, your data will be gone.
                    Always keep original copies of your CSV files and templates.
                </p>
            </section>

            <section>
                <h2>4. Email Delivery Disclaimer</h2>
                <p>
                    We provide an interface to connect with email providers (like Google). We are not responsible for emails being
                    flagged as spam, blocked by recipient servers, or failing to deliver due to provider API limits or outages.
                </p>
            </section>

            <section>
                <h2>5. Educational Use</h2>
                <p>
                    This project was built to solve a specific engineering problem. It is designed for use by organizers,
                    educators, and developers who understand the technical nature of local-first browser applications.
                </p>
            </section>
        </ContentLayout>
    );
}
